# Generated by Django 5.0.6 on 2024-07-13 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=15)),
                ('bday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('pday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.client')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.post')),
            ],
            options={
                'unique_together': {('c_id', 'p_id')},
            },
        ),
    ]
