# Generated by Django 5.0.6 on 2024-07-13 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_clientpost2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientPost2',
        ),
    ]
