# Generated by Django 5.0.6 on 2024-07-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_delete_clientpost2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['id'], name='i_Client_id'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['fname'], name='i_Client_fname'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['lname'], name='i_Client_lname'),
        ),
        migrations.AddIndex(
            model_name='clientpost',
            index=models.Index(fields=['c_id', 'p_id'], name='i_ClientPost_FoerignKeys'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['id'], name='i_Post_id'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['name'], name='i_Post_name'),
        ),
    ]
