# Generated by Django 5.0.6 on 2024-07-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_artist_album_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='name',
            field=models.CharField(default='not named', max_length=20),
        ),
    ]
