# Generated by Django 5.0.6 on 2024-07-14 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_song_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.artist'),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.artist')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='app1.album'),
        ),
    ]
