# Generated by Django 5.0.6 on 2024-07-15 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_song_artist_album_song_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
