# Generated by Django 5.0.6 on 2024-07-15 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_remove_song_song_remove_song_artist_delete_album_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReliabality',
            fields=[
                ('iday', models.DateField(primary_key=True, serialize=False)),
                ('reliablity', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='iday',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
