# Generated by Django 5.0.6 on 2024-07-15 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_clientsize'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientSize',
        ),
    ]
