# Generated by Django 5.0.6 on 2024-07-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_delete_clientsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSize',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('idsize', models.CharField(choices=[('A', 'xxs'), ('B', 'xs'), ('C', 's'), ('D', 'm'), ('E', 'l'), ('F', 'xl'), ('H', 'xxl')], max_length=1, unique=True)),
                ('size', models.CharField(choices=[('XXS', 'xxs'), ('XS', 'xs'), ('S', 's'), ('M', 'm'), ('L', 'l'), ('XL', 'xl'), ('XXL', 'xxl')], max_length=3)),
            ],
        ),
    ]
