# Generated by Django 5.0.6 on 2024-07-15 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_clientsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='size',
            field=models.ForeignKey(default='D', on_delete=django.db.models.deletion.PROTECT, to='app1.clientsize', to_field='idsize'),
        ),
        migrations.AlterField(
            model_name='clientsize',
            name='idsize',
            field=models.CharField(choices=[('A', 'xxs'), ('B', 'xs'), ('C', 's'), ('D', 'm'), ('E', 'l'), ('F', 'xl'), ('G', 'xxl')], max_length=1, unique=True),
        ),
    ]
