# Generated by Django 5.0.6 on 2024-07-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_clientsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsize',
            name='idsize',
            field=models.CharField(choices=[('A', 'xxs'), ('B', 'xs'), ('C', 's'), ('D', 'm'), ('E', 'l'), ('F', 'xl'), ('G', 'xxl')], max_length=1, unique=True),
        ),
    ]
