# Generated by Django 5.0.6 on 2024-07-15 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_remove_client_size_delete_clientsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSize',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('idsize', models.CharField(choices=[('A', 'xxs'), ('B', 'xs'), ('C', 's'), ('D', 'm'), ('E', 'l'), ('F', 'xl'), ('G', 'xxl')], max_length=1, unique=True)),
                ('size', models.CharField(choices=[('XXS', 'xxs'), ('XS', 'xs'), ('S', 's'), ('M', 'm'), ('L', 'l'), ('XL', 'xl'), ('XXL', 'xxl')], max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app1.clientsize', to_field='idsize'),
        ),
    ]
