# Generated by Django 5.0.6 on 2024-07-16 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_clientsize_client_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientReliabality',
        ),
    ]
