# Generated by Django 5.0.6 on 2024-07-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_delete_clientreliabality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsize',
            name='idsize',
            field=models.CharField(max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='clientsize',
            name='size',
            field=models.CharField(max_length=3),
        ),
    ]
