# Generated by Django 5.0.6 on 2024-07-17 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_alter_clientsize_idsize_alter_clientsize_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSalary',
            fields=[
                ('salary', models.IntegerField(primary_key=True, serialize=False)),
                ('rating', models.CharField(choices=[('A', 'class A'), ('B', 'class B'), ('C', 'class C'), ('D', 'class D')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='size',
        ),
        migrations.AddField(
            model_name='client',
            name='csalary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.clientsalary'),
        ),
        migrations.DeleteModel(
            name='ClientSize',
        ),
    ]
