# Generated by Django 5.0.6 on 2024-07-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_clientsalary_remove_client_size_client_csalary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='csalary',
            new_name='salary',
        ),
        migrations.AlterField(
            model_name='clientsalary',
            name='rating',
            field=models.CharField(choices=[('A', ''), ('B', ''), ('C', ''), ('D', ''), ('E', '')], max_length=1),
        ),
    ]
