# Generated by Django 5.0.6 on 2024-07-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_rename_csalary_client_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsalary',
            name='rating',
            field=models.CharField(choices=[('A', ''), ('B', ''), ('C', ''), ('D', ''), ('E', ''), ('F', '')], max_length=1),
        ),
        migrations.DeleteModel(
            name='ClientPost',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
