# Generated by Django 5.0.6 on 2024-07-19 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='fname',
        ),
    ]
