# Generated by Django 5.0.6 on 2024-07-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_rename_user_users_alter_clientsalary_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='age',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='lname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='fname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
